// This was initially generated by ChatGPT based on the original codes and the following instruction:
// "help me write integration tests for Dashboard and UserMenu"
// There were edits to fix issues and improve code coverage
import React from "react";
import { render, screen, within } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import Dashboard from "client/src/pages/user/Dashboard";
import { useAuth } from "client/src/context/auth";

jest.mock('client/src/context/auth', () => ({
    useAuth: jest.fn(() => [null, jest.fn()]) // Mock useAuth hook to return null state and a mock function for setAuth
}));

jest.mock("client/src/components/Layout", () => ({ children }) => (
  <div>LayoutMock {children}</div>
));

describe("Dashboard Integration with UserMenu", () => {
  it("renders user info and menu links", () => {
    useAuth.mockReturnValue([
      { user: { name: "John Doe", email: "john@test.com", address: "123 Street" } },
    ]);

    render(
      <MemoryRouter>
        <Dashboard />
      </MemoryRouter>
    );
    // Check UserMenu links
    expect(screen.getByText("Profile")).toBeInTheDocument();
    expect(screen.getByText("Orders")).toBeInTheDocument();

    // Check Dashboard info
    const dashboardCard = screen.getByTestId("dashboard-user-card");
    const cardQueries = within(dashboardCard);

    expect(cardQueries.getByText("John Doe")).toBeInTheDocument();
    expect(cardQueries.getByText("john@test.com")).toBeInTheDocument();
    expect(cardQueries.getByText("123 Street")).toBeInTheDocument();
  });
});