// This was generated by ChatGPT based on the original code and the following instruction:
// "help me write unit tests for this component:"
// There was some edits to fix minor issues.
import React from "react";
import { render, screen } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import AdminMenu from "client/src/components/AdminMenu.js";

describe("AdminMenu", () => {
  const setup = () =>
    render(
      <MemoryRouter>
        <AdminMenu />
      </MemoryRouter>
    );

  test("renders heading", () => {
    setup();
    expect(screen.getByText(/Admin Panel/i)).toBeInTheDocument();
  });

  test("renders all nav links", () => {
    setup();
    expect(
      screen.getByRole("link", { name: /Create Category/i })
    ).toBeInTheDocument();
    expect(
      screen.getByRole("link", { name: /Create Product/i })
    ).toBeInTheDocument();
    expect(
      screen.getByRole("link", { name: /Products/i })
    ).toBeInTheDocument();
    expect(
      screen.getByRole("link", { name: /Orders/i })
    ).toBeInTheDocument();
  });

  test("each link has the correct href", () => {
    setup();
    expect(
      screen.getByRole("link", { name: /Create Category/i })
    ).toHaveAttribute("href", "/dashboard/admin/create-category");
    expect(
      screen.getByRole("link", { name: /Create Product/i })
    ).toHaveAttribute("href", "/dashboard/admin/create-product");
    expect(screen.getByRole("link", { name: /Products/i })).toHaveAttribute(
      "href",
      "/dashboard/admin/products"
    );
    expect(screen.getByRole("link", { name: /Orders/i })).toHaveAttribute(
      "href",
      "/dashboard/admin/orders"
    );
  });
});
