// This was generated by ChatGPT based on the original code and the following instruction:
// "help me write unit tests for this component:"
// There was some edits to fix minor issues.
import React from "react";
import { render, screen } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import Footer from "../../src/components/Footer";

describe("Footer Component", () => {
  const setup = () =>
    render(
      <MemoryRouter>
        <Footer />
      </MemoryRouter>
    );

  test("renders copyright", () => {
    setup();
    expect(
      screen.getByText(/All Rights Reserved/i)
    ).toBeInTheDocument();
  });

  test("renders About link", () => {
    setup();
    const aboutLink = screen.getByText("About");
    expect(aboutLink).toBeInTheDocument();
    expect(aboutLink).toHaveAttribute("href", "/about");
  });

  test("renders Contact link", () => {
    setup();
    const contactLink = screen.getByText("Contact");
    expect(contactLink).toBeInTheDocument();
    expect(contactLink).toHaveAttribute("href", "/contact");
  });

  test("renders Privacy Policy link", () => {
    setup();
    const policyLink = screen.getByText("Privacy Policy");
    expect(policyLink).toBeInTheDocument();
    expect(policyLink).toHaveAttribute("href", "/policy");
  });
});
