// This was generated by ChatGPT based on the original code and the following instruction:
// "help me write unit tests for this component:"
// Edits were made to fix issues and improve coverage 
import React from "react";
import { render, screen } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import UserMenu from "client/src/components/UserMenu";

describe("UserMenu Component", () => {

    it("renders Dashboard heading", () => {

        render(
            <MemoryRouter>
                <UserMenu />
            </MemoryRouter>
        );

        expect(screen.getByText("Dashboard")).toBeInTheDocument();


    });

    it("renders Profile and Orders links with correct paths", () => {
        render(
            <MemoryRouter>
                <UserMenu />
            </MemoryRouter>
        );

        const profileLink = screen.getByRole("link", { name: /profile/i });
        const ordersLink = screen.getByRole("link", { name: /orders/i });
        expect(profileLink).toBeInTheDocument();
        expect(profileLink).toHaveAttribute("href", "/dashboard/user/profile");
        expect(ordersLink).toBeInTheDocument();
        expect(ordersLink).toHaveAttribute("href", "/dashboard/user/orders");

    });
});
