// This was generated by ChatGPT based on the original code and the following instruction:
// "help me write unit tests for this component:"
// There was some edits to fix minor issues.
import React from "react";
import { render, screen } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import About from "client/src/pages/About";

jest.mock("client/src/context/search", () => ({
  useSearch: () => [ {}, jest.fn() ],
}));
jest.mock("client/src/context/auth", () => ({
  useAuth: () => [null, jest.fn()],
}));
jest.mock("client/src/context/cart", () => ({
  useCart: () => [[], jest.fn()],
}));
jest.mock("client/src/hooks/useCategory", () => () => []);

describe("About Page", () => {
  const setup = () =>
    render(
      <MemoryRouter>
        <About />
      </MemoryRouter>
    );

  test("renders about image", () => {
    setup();
    const img = screen.getByAltText(/contactus/i);
    expect(img).toBeInTheDocument();
    expect(img).toHaveAttribute("src", "/images/about.jpeg");
  });

  test("renders about text", () => {
    setup();
    expect(screen.getByText(/Add text/i)).toBeInTheDocument();
  });
});
