// This was generated by ChatGPT based on the original code and the following instruction:
// "help me write unit tests for this component:"
// There was some edits to fix minor issues.
import React from "react";
import { render, screen } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import Contact from "client/src/pages/Contact";

jest.mock("client/src/context/search", () => ({
  useSearch: () => [ {}, jest.fn() ],
}));
jest.mock("client/src/context/auth", () => ({
  useAuth: () => [null, jest.fn()],
}));
jest.mock("client/src/context/cart", () => ({
  useCart: () => [[], jest.fn()],
}));
jest.mock("client/src/hooks/useCategory", () => () => []);

describe("Contact Page", () => {
  const setup = () =>
    render(
      <MemoryRouter>
        <Contact />
      </MemoryRouter>
    );

  test("renders contact heading", () => {
    setup();
    expect(screen.getByText(/CONTACT US/i)).toBeInTheDocument();
  });

  test("renders contact image", () => {
    setup();
    const img = screen.getByAltText(/contactus/i);
    expect(img).toBeInTheDocument();
    expect(img).toHaveAttribute("src", "/images/contactus.jpeg");
  });

  test("contact image has correct alt text", () => {
    setup();
    const img = screen.getByAltText("contactus");
    expect(img).toHaveAttribute("alt", "contactus");
  });

  test("renders email, phone, and support info", () => {
    setup();
    expect(screen.getByText(/www.help@ecommerceapp.com/i)).toBeInTheDocument();
    expect(screen.getByText(/012-3456789/i)).toBeInTheDocument();
    expect(screen.getByText(/1800-0000-0000/i)).toBeInTheDocument();
  });

  test("heading appears before contact info", () => {
    setup();
    const heading = screen.getByText(/CONTACT US/i);
    const email = screen.getByText(/www.help@ecommerceapp.com/i);
    expect(
      heading.compareDocumentPosition(email) &
        Node.DOCUMENT_POSITION_FOLLOWING
    ).toBeTruthy();
  });
});
