// This was generated by ChatGPT based on the original code and the following instruction:
// "help me write unit tests for this component:"
// There was some edits to fix minor issues.
import React from "react";
import { render, screen } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import Pagenotfound from "client/src/pages/Pagenotfound";

jest.mock("client/src/context/search", () => ({
  useSearch: () => [ {}, jest.fn() ],
}));
jest.mock("client/src/context/auth", () => ({
  useAuth: () => [null, jest.fn()],
}));
jest.mock("client/src/context/cart", () => ({
  useCart: () => [[], jest.fn()],
}));
jest.mock("client/src/hooks/useCategory", () => () => []);

describe("Pagenotfound Page", () => {
  const setup = () =>
    render(
      <MemoryRouter>
        <Pagenotfound />
      </MemoryRouter>
    );

  test("renders 404 title", () => {
    setup();
    expect(screen.getByText("404")).toBeInTheDocument();
  });

  test("renders not found heading", () => {
    setup();
    expect(screen.getByText(/Oops ! Page Not Found/i)).toBeInTheDocument();
  });

  test("renders Go Back link", () => {
    setup();
    const link = screen.getByText(/Go Back/i);
    expect(link).toBeInTheDocument();
    expect(link).toHaveAttribute("href", "/");
  });
});
