// This was generated by ChatGPT based on the original code and the following instruction:
// "help me write unit tests for this component:"
// There was some edits to fix minor issues.
import React from "react";
import { render, screen } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import Policy from "client/src/pages/Policy";

jest.mock("client/src/context/search", () => ({
  useSearch: () => [ {}, jest.fn() ],
}));
jest.mock("client/src/context/auth", () => ({
  useAuth: () => [null, jest.fn()],
}));
jest.mock("client/src/context/cart", () => ({
  useCart: () => [[], jest.fn()],
}));
jest.mock("client/src/hooks/useCategory", () => () => []);

describe("Policy Page", () => {
  const setup = () =>
    render(
      <MemoryRouter>
        <Policy />
      </MemoryRouter>
    );

  test("renders privacy policy image", () => {
    setup();
    const img = screen.getByAltText(/contactus/i);
    expect(img).toBeInTheDocument();
    expect(img).toHaveAttribute("src", "/images/contactus.jpeg");
  });

  test("renders privacy policy text", () => {
    setup();
    const policyTexts = screen.getAllByText(/add privacy policy/i);
    expect(policyTexts.length).toBeGreaterThanOrEqual(1);
  });
});
