// This was generated by ChatGPT based on the original code and the following instruction:
// "help me write unit tests for this component:"
// There was some edits to fix minor issues.
import connectDB from "./db";
import mongoose from "mongoose";

jest.mock("mongoose", () => ({
  connect: jest.fn(),
}));

describe("connectDB", () => {
  let logSpy;

  beforeEach(() => {
    logSpy = jest.spyOn(console, "log").mockImplementation(() => {});
    process.env.MONGO_URL = "mongodb://test-url";
  });

  afterEach(() => {
    logSpy.mockRestore();
    jest.clearAllMocks();
  });

  test("logs success message when connection succeeds", async () => {
    mongoose.connect.mockResolvedValue({ connection: { host: "localhost" } });
    await connectDB();
    expect(logSpy).toHaveBeenCalledWith(
      expect.stringContaining("Connected To Mongodb Database localhost")
    );
  });

  test("logs error message when connection fails", async () => {
    mongoose.connect.mockRejectedValue(new Error("fail"));
    await connectDB();
    expect(logSpy).toHaveBeenCalledWith(
      expect.stringContaining("Error in Mongodb")
    );
  });
});
