// This was generated by ChatGPT based on the original code and the following instruction:
// "help me write unit tests for this component:"
// Edits were made to fix issues and improve coverage 
import React from "react";
import { render, screen } from "@testing-library/react";
import Users from "client/src/pages/admin/Users";

// Mock Layout and AdminMenu so we can check if they render without full implementation
jest.mock("client/src/components/Layout", () => ({ children }) => (
  <div>Mocked Layout {children}</div>
));
jest.mock("client/src/components/AdminMenu", () => () => <div>Mocked AdminMenu</div>);

describe("Users Component", () => {
  it("renders All Users heading", () => {
    render(<Users />);
    expect(screen.getByText("All Users")).toBeInTheDocument();
  });

  it("renders AdminMenu component", () => {
    render(<Users />);
    expect(screen.getByText("Mocked AdminMenu")).toBeInTheDocument();
  });

  it("passes correct title prop to Layout", () => {
    render(<Users />);
    expect(screen.getByText("Mocked Layout")).toBeInTheDocument();
  });
});