// This was generated by ChatGPT based on the original code and the following instruction:
// "help me write unit tests for this component:"
// Edits were made to fix issues and improve coverage
import React from "react";
import { render, screen, waitFor } from "@testing-library/react";
import { useAuth } from "client/src/context/auth";
import axios from "axios";
import AdminRoute from "client/src/components/Routes/AdminRoute.js";
import { Outlet } from "react-router-dom";
import Spinner from "client/src/components/Spinner.js";

// Mock dependencies
jest.mock("axios");

jest.mock("client/src/context/auth", () => ({
  useAuth: jest.fn(() => [null, jest.fn()]), // default mock
}));

jest.mock("client/src/components/Spinner.js", () =>
  jest.fn(() => <div data-testid="spinner">Loading...</div>)
);

jest.mock("react-router-dom", () => ({
  Outlet: jest.fn(() => <div data-testid="outlet">Protected Route</div>),
}));

describe("AdminRoute", () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  it("renders Spinner when no auth token", () => {
    useAuth.mockReturnValue([{ token: null }, jest.fn()]);

    render(<AdminRoute />);
    expect(screen.getByTestId("spinner")).toBeInTheDocument();
  });

  it("renders Spinner while checking admin auth", async () => {
    useAuth.mockReturnValue([{ token: "testtoken" }, jest.fn()]);
    axios.get.mockResolvedValueOnce({ data: { ok: false } });

    render(<AdminRoute />);
    expect(screen.getByTestId("spinner")).toBeInTheDocument();
  });

  it("renders Outlet when admin auth check passes", async () => {
    useAuth.mockReturnValue([{ token: "testtoken" }, jest.fn()]);
    axios.get.mockResolvedValueOnce({ data: { ok: true } });

    render(<AdminRoute />);

    await waitFor(() => {
      expect(screen.getByTestId("outlet")).toBeInTheDocument();
    });
  });

  it("renders Spinner when admin auth check fails", async () => {
    useAuth.mockReturnValue([{ token: "testtoken" }, jest.fn()]);
    axios.get.mockResolvedValueOnce({ data: { ok: false } });

    render(<AdminRoute />);

    await waitFor(() => {
      expect(screen.getByTestId("spinner")).toBeInTheDocument();
    });
  });
});
