// This was initially generated by ChatGPT based on the original codes and the following instruction:
// "help me write integration tests for AdminOrders and AdminMenu"
// There were edits to fix issues.
import React from "react";
import { render, screen, waitFor } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import AdminOrders from "client/src/pages/admin/AdminOrders";

// mock axios + toast
jest.mock("axios");
jest.mock("react-hot-toast", () => ({
  success: jest.fn(),
  error: jest.fn(),
}));
jest.mock("client/src/components/Layout", () => ({ children }) => (
  <div>Mocked Layout {children}</div>
));

// mock useAuth
let mockAuthValue;
jest.mock("client/src/context/auth", () => ({
  useAuth: () => [mockAuthValue, jest.fn()],
}));

describe("AdminMenu Integration", () => {
  beforeEach(() => {
    jest.resetAllMocks();
    mockAuthValue = { token: "valid-token", user: { name: "Admin", role: 1 } };
  });
  test("renders all admin links correctly", async () => {
    render(
      <MemoryRouter>
        <AdminOrders />
      </MemoryRouter>
    );

    // Heading
    await waitFor(() => { 
      expect(screen.getByText("Admin Panel")).toBeInTheDocument();
      // Link texts
      const links = [
        { text: "Create Category", href: "/dashboard/admin/create-category" },
        { text: "Create Product", href: "/dashboard/admin/create-product" },
        { text: "Products", href: "/dashboard/admin/products" },
        { text: "Orders", href: "/dashboard/admin/orders" },
      ];

      links.forEach(({ text, href }) => {
        const linkEl = screen.getByRole("link", { name: text });
        expect(linkEl).toBeInTheDocument();
        expect(linkEl.getAttribute("href")).toBe(href);
      });
    });
  });
});