// This was initially generated by ChatGPT based on the original codes and the following instruction:
// "help me write integration tests for AdminDashboard and AdminMenu"
// There were edits to fix issues.
import React from "react";
import { render, screen, waitFor } from "@testing-library/react";
import AdminDashboard from "client/src/pages/admin/AdminDashboard";
import { MemoryRouter } from "react-router-dom";
import { useAuth } from "client/src/context/auth";

// Mock components
jest.mock("client/src/components/Layout", () => ({ children }) => (
  <div>Mocked Layout {children}</div>
));

jest.mock("client/src/context/auth");

describe("AdminMenu Integration", () => {
  test("renders all admin links correctly", async () => {
    useAuth.mockReturnValue([
          {
            user: {
              name: "Alice",
              email: "alice@example.com",
              phone: "1234567890",
            },
          },
        ]);
    render(
      <MemoryRouter>
        <AdminDashboard />
      </MemoryRouter>
    );

    // Heading
    await waitFor(() => { 
      expect(screen.getByText("Admin Panel")).toBeInTheDocument();
      // Link texts
      const links = [
        { text: "Create Category", href: "/dashboard/admin/create-category" },
        { text: "Create Product", href: "/dashboard/admin/create-product" },
        { text: "Products", href: "/dashboard/admin/products" },
        { text: "Orders", href: "/dashboard/admin/orders" },
      ];

      links.forEach(({ text, href }) => {
        const linkEl = screen.getByRole("link", { name: text });
        expect(linkEl).toBeInTheDocument();
        expect(linkEl.getAttribute("href")).toBe(href);
      });
    });
  });
});