// This was initially generated by ChatGPT based on the original codes and the following instruction:
// "help me write integration tests for CreateProduct and AdminMenu"
// There were edits to fix issues.
import React from "react";
import { render, screen, fireEvent, waitFor } from "@testing-library/react";
import CreateProduct from "client/src/pages/admin/CreateProduct";
import { MemoryRouter } from "react-router-dom";

// 🔹 Mock dependencies
jest.mock("axios");
jest.mock("react-hot-toast", () => ({
  success: jest.fn(),
  error: jest.fn(),
}));
jest.mock("react-router-dom", () => ({
  ...jest.requireActual("react-router-dom"),
  useNavigate: jest.fn(),
}));
jest.mock("client/src/components/Layout", () => ({ children }) => (
  <div>Mocked Layout {children}</div>
));

describe("AdminMenu Integration", () => {
  test("renders all admin links correctly", async () => {
    render(
      <MemoryRouter>
        <CreateProduct />
      </MemoryRouter>
    );

    // Heading
    await waitFor(() => { 
      expect(screen.getByText("Admin Panel")).toBeInTheDocument();
      // Link texts
      const links = [
        { text: "Create Category", href: "/dashboard/admin/create-category" },
        { text: "Create Product", href: "/dashboard/admin/create-product" },
        { text: "Products", href: "/dashboard/admin/products" },
        { text: "Orders", href: "/dashboard/admin/orders" },
      ];

      links.forEach(({ text, href }) => {
        const linkEl = screen.getByRole("link", { name: text });
        expect(linkEl).toBeInTheDocument();
        expect(linkEl.getAttribute("href")).toBe(href);
      });
    });
  });
});
