// This was initially generated by ChatGPT based on the original codes and the following instruction:
// "Help me write integration test between the Login and auth context component"
// There were edits to fix issues.
import React from "react";
import { screen, render, fireEvent, waitFor } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import axios from "axios";
import Login from "../../../src/pages/Auth/Login";
import { AuthProvider, useAuth } from "../../../src/context/auth";
import toast from "react-hot-toast";
import { renderWithProviders } from "../../testUtils";
import { useLocation } from "react-router-dom";
import Header from "../../../src/components/Header";
import { Routes, Route } from "react-router-dom";
import Forget from "../../../src/pages/Auth/Forget";

// Mock dependencies
jest.mock("axios");
jest.mock("react-hot-toast");

// Mock Layout component and its dependencies
jest.mock("../../../src/components/Layout", () => {
  return function Layout({ children }) {
    return <div data-testid="layout">{children}</div>;
  };
});

// Component to test auth context state
const AuthContextTester = () => {
  const [auth] = useAuth();
  return (
    <div data-testid="auth-context-tester">
      <span data-testid="auth-user">{JSON.stringify(auth.user)}</span>
      <span data-testid="auth-token">{auth.token}</span>
    </div>
  );
};

describe("Login", () => {
  beforeEach(() => {
    // Clear all mocks before each test
    jest.clearAllMocks();
    localStorage.clear();

    // Mock toast methods
    toast.success = jest.fn();
    toast.error = jest.fn();
  });

  test("Auth Context Integration. Successful login response will result in the auth context containing the correct user information", async () => {
    // Arrange: Mock successful API response
    const mockUserData = {
      _id: "123456",
      name: "Test User",
      email: "test@example.com",
      phone: "1234567890",
      address: "123 Test St",
      role: 0,
    };

    const mockResponse = {
      data: {
        success: true,
        message: "login successfully",
        user: mockUserData,
        token: "mock-jwt-token-12345",
      },
    };

    axios.post.mockResolvedValueOnce(mockResponse);

    // Act: Render Login component wrapped with AuthProvider
    const { getByPlaceholderText, getByText, getByTestId } = render(
      <AuthProvider>
        <MemoryRouter>
          <Login />
          <AuthContextTester />
        </MemoryRouter>
      </AuthProvider>
    );

    // Fill in the form
    const emailInput = getByPlaceholderText("Enter Your Email");
    const passwordInput = getByPlaceholderText("Enter Your Password");
    const loginButton = getByText("LOGIN");

    fireEvent.change(emailInput, {
      target: { value: "test@example.com" },
    });
    fireEvent.change(passwordInput, {
      target: { value: "password123" },
    });

    // Submit the form
    fireEvent.click(loginButton);

    // Assert: Wait for the auth context to be updated
    await waitFor(() => {
      const authUser = getByTestId("auth-user");
      const authToken = getByTestId("auth-token");

      // Verify auth context contains correct user information
      expect(authUser.textContent).toBe(JSON.stringify(mockUserData));
      expect(authToken.textContent).toBe("mock-jwt-token-12345");
    });

    // Verify axios was called with correct parameters
    expect(axios.post).toHaveBeenCalledWith("/api/v1/auth/login", {
      email: "test@example.com",
      password: "password123",
    });

    // Verify success toast was shown
    expect(toast.success).toHaveBeenCalledWith("login successfully", {
      duration: 5000,
      icon: "🙏",
      style: {
        background: "green",
        color: "white",
      },
    });

    // Verify localStorage was updated
    const storedAuth = JSON.parse(localStorage.getItem("auth"));
    expect(storedAuth).toEqual({
      user: mockUserData,
      token: "mock-jwt-token-12345",
    });
  });

  test("Navigates to the login page when header Login tab is clicked", async () => {
    const LocationDisplay = () => {
      const location = useLocation();
      return <div data-testid="location-display">{location.pathname}</div>;
    };

    renderWithProviders(
      <Routes>
        <Route
          path="/"
          element={
            <>
              <Header />
              <LocationDisplay />
              <div data-testid="home-page">Home Page</div>
            </>
          }
        />
        <Route
          path="/login"
          element={
            <>
              <Header />
              <LocationDisplay />
              <Login />
            </>
          }
        />
      </Routes>,
      { route: "/" }
    );

    // Navigate from home page to Login
    expect(screen.getByTestId("location-display").textContent).toBe("/");
    expect(screen.getByTestId("home-page")).toBeInTheDocument();

    const headerLoginLink = screen.getByRole("link", { name: /login/i });
    expect(headerLoginLink).toBeVisible();
    fireEvent.click(headerLoginLink);

    // Wait for navigation to complete and Login page to render
    await waitFor(() => {
      expect(screen.getByTestId("location-display").textContent).toBe("/login");
    });

    expect(
      screen.getByRole("heading", { name: /LOGIN FORM/i })
    ).toBeInTheDocument();
    expect(screen.getByPlaceholderText("Enter Your Email")).toBeInTheDocument();
    expect(
      screen.getByPlaceholderText("Enter Your Password")
    ).toBeInTheDocument();
  });

  test("Navigates to the forget page when forget-password button clicked", async () => {
    const LocationDisplay = () => {
      const location = useLocation();
      return <div data-testid="location-display">{location.pathname}</div>;
    };

    const { getByRole, getByText } = renderWithProviders(
      <Routes>
        <Route
          path="/login"
          element={
            <>
              <Header />
              <LocationDisplay />
              <Login />
            </>
          }
        />
        <Route
          path="/forgot-password"
          element={
            <>
              <Header />
              <LocationDisplay />
              <Forget />
            </>
          }
        />
      </Routes>,
      { route: "/login" }
    );

    // check if at login page first
    expect(screen.getByTestId("location-display").textContent).toBe("/login");
    const forgetButton = getByRole("button", { name: "Forgot Password" });
    fireEvent.click(forgetButton);

    await waitFor(() => {
      expect(screen.getByTestId("location-display").textContent).toBe(
        "/forgot-password"
      );
    });

    expect(
      screen.getByRole("heading", { name: /RESET PASSWORD/i })
    ).toBeInTheDocument();
    expect(screen.getByPlaceholderText("Enter Your Email")).toBeInTheDocument();
    expect(
      screen.getByPlaceholderText("Enter Your Answer")
    ).toBeInTheDocument();
    expect(
      screen.getByPlaceholderText("Enter New Password")
    ).toBeInTheDocument();
  });
});
