// This was initially generated by ChatGPT based on the original codes and the following instruction:
// "help me write integration tests for Users and AdminMenu"
// There were edits to fix issues and improve code coverage
import React from "react";
import { render, screen } from "@testing-library/react";
import { MemoryRouter } from "react-router-dom";
import Users from "client/src/pages/admin/Users";
import AdminMenu from "client/src/components/AdminMenu";

jest.mock('client/src/context/auth', () => ({
    useAuth: jest.fn(() => [null, jest.fn()]) // Mock useAuth hook to return null state and a mock function for setAuth
}));

jest.mock("client/src/components/Layout", () => ({ children }) => (
    <div>LayoutMock {children}</div>
));

// Integration Test: Users page + AdminMenu
describe("Users Page Integration Test", () => {
  test("renders Users page with AdminMenu links", () => {
    render(
      <MemoryRouter>
        <Users />
      </MemoryRouter>
    );

    // Check if page title exists
    expect(screen.getByText("All Users")).toBeInTheDocument();

    // Check if AdminMenu links are rendered
    expect(screen.getByText("Admin Panel")).toBeInTheDocument();
    expect(screen.getByText("Create Category")).toBeInTheDocument();
    expect(screen.getByText("Create Product")).toBeInTheDocument();
    expect(screen.getByText("Products")).toBeInTheDocument();
    expect(screen.getByText("Orders")).toBeInTheDocument();
  });

  test("AdminMenu links have correct href", () => {
    render(
      <MemoryRouter>
        <AdminMenu />
      </MemoryRouter>
    );

    expect(screen.getByText("Create Category").closest("a")).toHaveAttribute(
      "href",
      "/dashboard/admin/create-category"
    );
    expect(screen.getByText("Create Product").closest("a")).toHaveAttribute(
      "href",
      "/dashboard/admin/create-product"
    );
    expect(screen.getByText("Products").closest("a")).toHaveAttribute(
      "href",
      "/dashboard/admin/products"
    );
    expect(screen.getByText("Orders").closest("a")).toHaveAttribute(
      "href",
      "/dashboard/admin/orders"
    );
  });
});
